spring:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 1000MB
file:
  upload:
    acceptableVideoExtensions: mp4,mov,avi,wmv
    acceptableImageExtensions: jpg,png,jpeg

minio:
  url: http://127.0.0.1:9000/
  bucket: user
  access-key: test
  secret-key: test1234
  image-folder: profpic/
  video-folder: video/
application:
  swagger:
    title: MinIo Photo API
    description: Spring Boot photo uploading with MinIo file storage.
    version: 0.0.2
    cors:
      allowedOrigins: "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders: "*"
