version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: test1234
    command: server --console-address :9001 /data
  create_buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c '
      sleep 5;
      /usr/bin/mc config host add s3 http://minio:9001 test test1234 --api S3v4;
      /usr/bin/mc mb user;
      [[ ! -z "`/usr/bin/mc ls s3 | grep user`" ]] || /usr/bin/mc mb s3/user;
      /usr/bin/mc policy download s3/user;
      exit 0;
      '