version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: test1234
    command: server --console-address :9001 /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 test test1234;
      /usr/bin/mc mb myminio/user;
      /usr/bin/mc policy set public myminio/user;
      exit 0;
      "